class Ritual {
  final String nome;
  final String elemento;
  final int circulo;
  final String execucao;
  final String alcance;
  final String alvoAreaEfeito;
  final String duracao;
  final String resistencia;
  final String descricao;
  final String discente;
  final String verdadeiro;
  final int custoPE;
  
  // NOVOS CAMPOS PARA CUSTO CUSTOMIZADO
  final int? custoDiscente; 
  final int? custoVerdadeiro;

  Ritual({
    required this.nome,
    required this.elemento,
    required this.circulo,
    required this.execucao,
    required this.alcance,
    required this.alvoAreaEfeito,
    required this.duracao,
    this.resistencia = "Nenhuma",
    required this.descricao,
    this.discente = "Nenhum",
    this.verdadeiro = "Nenhum",
    this.custoPE = 1,
    this.custoDiscente,
    this.custoVerdadeiro,
  });

  Map<String, dynamic> toJson() => {
        'nome': nome,
        'elemento': elemento,
        'circulo': circulo,
        'execucao': execucao,
        'alcance': alcance,
        'alvoAreaEfeito': alvoAreaEfeito,
        'duracao': duracao,
        'resistencia': resistencia,
        'descricao': descricao,
        'discente': discente,
        'verdadeiro': verdadeiro,
        'custoPE': custoPE,
        'custoDiscente': custoDiscente,
        'custoVerdadeiro': custoVerdadeiro,
      };

  factory Ritual.fromJson(Map<String, dynamic> json) => Ritual(
        nome: json['nome'] ?? '',
        elemento: json['elemento'] ?? '',
        circulo: json['circulo'] ?? 1,
        execucao: json['execucao'] ?? '',
        alcance: json['alcance'] ?? '',
        alvoAreaEfeito: json['alvoAreaEfeito'] ?? '',
        duracao: json['duracao'] ?? '',
        resistencia: json['resistencia'] ?? 'Nenhuma',
        descricao: json['descricao'] ?? '',
        discente: json['discente'] ?? 'Nenhum',
        verdadeiro: json['verdadeiro'] ?? 'Nenhum',
        custoPE: json['custoPE'] ?? 1,
        custoDiscente: json['custoDiscente'],
        custoVerdadeiro: json['custoVerdadeiro'],
      );
}

final List<Ritual> catalogoRituais = [
  Ritual(
    nome: "Amaldiçoar Arma",
    elemento: "Variável", // CONHECIMENTO, ENERGIA, MORTE ou SANGUE
    circulo: 1,
    execucao: "Padrão",
    alcance: "Toque",
    alvoAreaEfeito: "Alvo: 1 arma corpo a corpo ou pacote de munição",
    duracao: "Cena",
    descricao: "Quando aprender este ritual, escolha um elemento entre Conhecimento, Energia, Morte e Sangue. Este ritual passa a ser do elemento escolhido. Você imbui a arma ou munições com o elemento, fazendo com que causem +1d6 de dano do tipo do elemento.",
    discente: "(+2 PE): muda o bônus de dano para +2d6. Requer 2º círculo.",
    verdadeiro: "(+5 PE): muda o bônus de dano para +4d6. Requer 3º círculo e afinidade.",
  ),
  Ritual(
    nome: "Amaldiçoar Tecnologia",
    elemento: "Energia",
    circulo: 1,
    execucao: "Padrão",
    alcance: "Toque",
    alvoAreaEfeito: "Alvo: 1 acessório ou arma de fogo",
    duracao: "Cena",
    descricao: "Você imbui o alvo com Energia, fazendo-o funcionar acima de sua capacidade. O item recebe uma modificação a sua escolha.",
    discente: "(+2 PE): muda para duas modificações. Requer 2º círculo.",
    verdadeiro: "(+5 PE): muda para três modificações. Requer 3º círculo e afinidade.",
  ),
  Ritual(
    nome: "Arma Atroz",
    elemento: "Sangue",
    circulo: 1,
    execucao: "Padrão",
    alcance: "Toque",
    alvoAreaEfeito: "Alvo: 1 arma corpo a corpo",
    duracao: "Sustentada",
    descricao: "A arma é recoberta por veias carmesim e passa a exalar uma aura de violência. Ela fornece +2 em testes de ataque e +1 na margem de ameaça.",
    discente: "(+2 PE): muda o bônus para +5 em testes de ataque. Requer 2º círculo.",
    verdadeiro: "(+5 PE): muda o bônus para +5 em testes de ataque e +2 na margem de ameaça e no multiplicador de crítico. Requer 3º círculo e afinidade.",
  ),
  Ritual(
    nome: "Armadura de Sangue",
    elemento: "Sangue",
    circulo: 1,
    execucao: "Padrão",
    alcance: "Pessoal",
    alvoAreaEfeito: "Alvo: Você",
    duracao: "Cena",
    descricao: "Seu sangue escorre para fora do corpo, cobrindo-o sob a forma de uma carapaça que fornece +5 em Defesa. Esse bônus é cumulativo com outros rituais, mas não com bônus fornecido por equipamento.",
    discente: "(+5 PE): muda o efeito para “fornece +10 na Defesa e resistência a balístico, corte, impacto e perfuração 5”. Requer 3º círculo.",
    verdadeiro: "(+9 PE): muda o efeito para “fornece +15 na Defesa e resistência a balístico, corte, impacto e perfuração 10”. Requer 4º círculo e afinidade.",
  ),
  Ritual(
    nome: "Cicatrização",
    elemento: "Morte",
    circulo: 1,
    execucao: "Padrão",
    alcance: "Toque",
    alvoAreaEfeito: "Alvo: 1 ser",
    duracao: "Instantânea",
    descricao: "Você acelera o tempo ao redor das feridas do alvo, que cicatrizam instantaneamente. O alvo recupera 3d8+3 PV, mas envelhece 1 ano automaticamente.",
    discente: "(+2 PE): aumenta a cura para 5d8+5 PV. Requer 2º círculo.",
    verdadeiro: "(+9 PE): muda o alcance para “curto”, o alvo para “seres escolhidos” e aumenta a cura para 7d8+7 PV. Requer 4º círculo e afinidade com Morte.",
  ),
  Ritual(
    nome: "Cinerária",
    elemento: "Medo",
    circulo: 1,
    execucao: "Padrão",
    alcance: "Curto",
    alvoAreaEfeito: "Área: Nuvem de 6m de raio",
    duracao: "Cena",
    descricao: "Você manifesta uma névoa carregada de essência paranormal. Rituais conjurados dentro da névoa têm sua DT aumentada em +5.",
    discente: "(+2 PE): além do normal, rituais conjurados dentro da névoa custam –2 PE.",
    verdadeiro: "(+5 PE): além do normal, rituais conjurados dentro da névoa causam dano maximizado.",
  ),
  Ritual(
    nome: "Coincidência Forçada",
    elemento: "Energia",
    circulo: 1,
    execucao: "Padrão",
    alcance: "Curto",
    alvoAreaEfeito: "Alvo: 1 ser",
    duracao: "Cena",
    descricao: "Você manipula os caminhos do caos para que o alvo tenha mais sorte. O alvo recebe +2 em testes de perícias.",
    discente: "(+2 PE): muda o alvo para aliados à sua escolha. Requer 2º círculo.",
    verdadeiro: "(+5 PE): muda o alvo para aliados à sua escolha e o bônus para +5. Requer 3º círculo e afinidade.",
  ),
  Ritual(
    nome: "Compreensão Paranormal",
    elemento: "Conhecimento",
    circulo: 1,
    execucao: "Padrão",
    alcance: "Toque",
    alvoAreaEfeito: "Alvo: 1 ser ou objeto",
    duracao: "Cena",
    resistencia: "Vontade anula (veja texto)",
    descricao: "O ritual confere a você compreensão sobrenatural da linguagem. Se tocar um objeto contendo informação (ou livro, um dispositivo com uma gravação…), você entende as palavras mesmo que não conheça seu idioma, contanto que se trate de um idioma humano (não funciona com símbolos ou sigilos paranormais). Se tocar uma pessoa, pode se comunicar com ela como se falassem um idioma em comum. Se tocar um ser não inteligente, como um animal, pode perceber seus sentimentos básicos, como medo ou felicidade. Um alvo involuntário tem direito a um teste de Vontade.",
    discente: "(+2 PE): muda o alcance para “curto” e o alvo para “alvos escolhidos”. Você pode entender todos os alvos afetados. Requer 2º círculo.",
    verdadeiro: "(+5 PE): muda o alcance para “pessoal” e o alvo para “você”. Em vez do normal, você pode falar, entender e escrever qualquer idioma humano. Requer 3º círculo.",
  ),
  Ritual(
    nome: "Consumir Manancial",
    elemento: "Morte",
    circulo: 1,
    execucao: "Padrão",
    alcance: "Pessoal",
    alvoAreaEfeito: "Alvo: Você",
    duracao: "Instantânea",
    descricao: "Você suga uma pequena porção do tempo de vida de plantas, insetos e até mesmo do solo ao redor, gerando Lodo e recebendo 3d6 pontos de vida temporários. Os PV temporários desaparecem ao final da cena.",
    discente: "(+2 PE): muda os PV temporários recebidos para 6d6. Requer 2º círculo.",
    verdadeiro: "(+5 PE): muda o alvo para “área: esfera com 6m de raio centrada em você” e a resistência para “Fortitude reduz à metade”. Em vez do normal, você suga energia de todos os seres vivos na área, causando 3d6 pontos de dano de Morte em cada um e recebendo PV temporários iguais ao dano total causado até o final da cena. Requer 3º círculo e afinidade.",
  ),
  Ritual(
    nome: "Corpo Adaptado",
    elemento: "Sangue",
    circulo: 1,
    execucao: "Padrão",
    alcance: "Toque",
    alvoAreaEfeito: "Alvo: 1 pessoa ou animal",
    duracao: "Cena",
    descricao: "Este ritual modifica a biologia do alvo para permitir a sobrevivência em ambientes hostis. O alvo fica imune a calor e frio extremos, pode respirar na água se respirar ar (ou vice-versa) e não sufoca em fumaça densa.",
    discente: "(+2 PE): muda a duração para 1 dia.",
    verdadeiro: "(+5 PE): muda o alcance para “curto” e o alvo para “pessoas ou animais escolhidos”.",
  ),
  Ritual(
    nome: "Decadência",
    elemento: "Morte",
    circulo: 1,
    execucao: "Padrão",
    alcance: "Toque",
    alvoAreaEfeito: "Alvo: 1 ser",
    duracao: "Instantânea",
    resistencia: "Fortitude reduz à metade",
    descricao: "Espirais de trevas envolvem sua mão e definham o alvo, que sofre 2d8+2 pontos de dano de Morte.",
    discente: "(+2 PE): muda a resistência para “nenhuma” e o dano para 3d8+3. Como parte da execução do ritual, você transfere as espirais para uma arma e faz um ataque corpo a corpo contra o alvo com esta arma. Se acertar, causa o dano da arma e do ritual, somados.",
    verdadeiro: "(+5 PE): muda o alcance para “pessoal” o alvo para “área: explosão com 6m de raio” e o dano para 8d8+8. As espirais afetam todos os seres na área. Requer 3º círculo.",
  ),
  Ritual(
    nome: "Definhar",
    elemento: "Morte",
    circulo: 1,
    execucao: "Padrão",
    alcance: "Curto",
    alvoAreaEfeito: "Alvo: 1 ser",
    duracao: "Cena",
    resistencia: "Fortitude parcial",
    descricao: "Você dispara uma lufada de cinzas que drena as forças do alvo. O alvo fica fatigado. Se passar no teste de resistência, em vez disso fica vulnerável.",
    discente: "(+2 PE): em vez do normal, o alvo fica exausto. Se passar na resistência, fica fatigado. Requer 2º círculo.",
    verdadeiro: "(+5 PE): como discente, mas muda o alvo para “até 5 seres”. Requer 3º círculo e afinidade com Morte.",
  ),
  Ritual(
    nome: "Distorcer Aparência",
    elemento: "Sangue",
    circulo: 1,
    execucao: "Padrão",
    alcance: "Pessoal",
    alvoAreaEfeito: "Alvo: Você",
    duracao: "Cena",
    resistencia: "Vontade desacredita",
    descricao: "Você modifica sua aparência de modo a parecer outra pessoa. Isso inclui altura, peso, tom de pele, cor de cabelo, timbre de voz, impressão digital, córnea etc. Você recebe +10 em testes de Enganação para disfarce, mas não recebe habilidades da nova forma nem modifica suas demais estatísticas.",
    discente: "(+2 PE): muda o alcance para “curto” e o alvo para “1 ser”. Um alvo involuntário pode anular o efeito com um teste de Vontade.",
    verdadeiro: "(+5 PE): como em Discente, mas muda o alvo para “seres escolhidos”. Requer 3º círculo.",
  ),
  Ritual(
    nome: "Eletrocussão",
    elemento: "Energia",
    circulo: 1,
    execucao: "Padrão",
    alcance: "Curto",
    alvoAreaEfeito: "Alvo: 1 ser ou objeto",
    duracao: "Instantânea",
    resistencia: "Fortitude parcial",
    descricao: "Você manifesta e dispara uma corrente elétrica contra o alvo, que sofre 3d6 pontos de dano de eletricidade e fica vulnerável por uma rodada. Se passar no teste de resistência, sofre apenas metade do dano e evita a condição. Se usado contra objetos eletrônicos, este ritual causa o dobro de dano e ignora resistência.",
    discente: "(+2 PE): muda o alvo para “área: linha de 30m”. Você dispara um poderoso raio que causa 6d6 pontos de dano de Energia em todos os seres e objetos livres na área. Requer 2º círculo.",
    verdadeiro: "(+5 PE): muda o alvo para “alvos escolhidos”. Em vez do normal, você dispara vários relâmpagos, um para cada alvo escolhido, causando 8d6 pontos de dano de Energia em cada. Requer 3º círculo.",
  ),
  Ritual(
    nome: "Embaralhar",
    elemento: "Energia",
    circulo: 1,
    execucao: "Padrão",
    alcance: "Pessoal",
    alvoAreaEfeito: "Alvo: Você",
    duracao: "Cena",
    descricao: "Você cria três cópias ilusórias suas, como hologramas extremamente realistas. As cópias ficam ao seu redor e imitam suas ações, tornando difícil para um inimigo saber quem é o verdadeiro. Você recebe +6 na Defesa. Cada vez que um ataque contra você erra, uma das imagens desaparece e o bônus na Defesa diminui em 2. Um oponente deve ver as cópias para ser confundido. Se você estiver invisível, ou o atacante fechar os olhos, você não recebe o bônus (mas o atacante sofre as penalidades normais por não enxergar).",
    discente: "(+2 PE): muda o número de cópias para 5 (e o bônus na Defesa para +10). Requer 2º círculo.",
    verdadeiro: "(+5 PE): muda o número de cópias para 8 (e o bônus na Defesa para +16). Além do normal, toda vez que uma cópia é destruída, emite um clarão de luz. O ser que destruiu a cópia fica ofuscado por uma rodada. Requer 3º círculo.",
  ),
  Ritual(
    nome: "Enfeitiçar",
    elemento: "Conhecimento",
    circulo: 1,
    execucao: "Padrão",
    alcance: "Curto",
    alvoAreaEfeito: "Alvo: 1 pessoa",
    duracao: "Cena",
    resistencia: "Vontade anula",
    descricao: "Este ritual torna o alvo prestativo. Ele não fica sob seu controle, mas percebe suas palavras e ações da maneira mais favorável possível. Você recebe um bônus de +10 em testes de Diplomacia com ele. Um alvo hostil ou que esteja envolvido em combate recebe +5 em seu teste de resistência. Se você ou seus aliados tomarem qualquer ação hostil contra o alvo, o efeito é dissipado e o alvo retorna à atitude que tinha antes (ou piorada, de acordo com o mestre).",
    discente: "(+2 PE): em vez do normal, você sugere uma ação para o alvo e ele obedece. A sugestão deve ser feita de modo que pareça aceitável, a critério do mestre. Pedir que o alvo atire em seu companheiro, por exemplo, dissipa o efeito. Já sugerir a um guarda que descanse um pouco, de modo que você e seus aliados passem por ele, é aceitável. Quando o alvo executa a ação, o efeito termina. Você pode determinar uma condição específica para a sugestão: por exemplo, que o policial prenda a próxima pessoa de casaco verde que ele encontrar. Requer 2º círculo.",
    verdadeiro: "(+5 PE): afeta todos os alvos dentro do alcance. Requer 3º círculo.",
  ),
  Ritual(
    nome: "Espirais da Perdição",
    elemento: "Morte",
    circulo: 1,
    execucao: "Padrão",
    alcance: "Curto",
    alvoAreaEfeito: "Alvo: 1 ser",
    duracao: "Cena",
    descricao: "Espirais surgem no corpo do alvo, tornando seus movimentos lentos. O alvo sofre –1d20 em testes de ataque.",
    discente: "(+2 PE): muda a penalidade para –2d20. Requer 2º círculo.",
    verdadeiro: "(+8 PE): muda a penalidade para –2d20. e o alvo para “seres escolhidos”. Requer 3º círculo.",
  ),
  Ritual(
    nome: "Fortalecimento Sensorial",
    elemento: "Sangue",
    circulo: 1,
    execucao: "Padrão",
    alcance: "Pessoal",
    alvoAreaEfeito: "Alvo: Você",
    duracao: "Cena",
    descricao: "Você potencializa seus sentidos, recebendo +1d20 em Investigação, Luta, Percepção e Pontaria.",
    discente: "(+2 PE): além do normal, seus inimigos sofrem –1d20 em testes de ataque contra você. Requer 2º círculo.",
    verdadeiro: "(+5 PE): além do normal, você apura seus sentidos para perceber perigo. Você fica imune às condições surpreendido e desprevenido e recebe +10 em Defesa e Reflexos. Requer 4º círculo e afinidade.",
  ),
  Ritual(
    nome: "Luz",
    elemento: "Energia",
    circulo: 1,
    execucao: "Padrão",
    alcance: "Curto",
    alvoAreaEfeito: "Alvo: 1 objeto",
    duracao: "Cena",
    resistencia: "Vontade anula (veja texto)",
    descricao: "O alvo emite luz de cores alternadas e brilhantes (mas não produz calor) em uma área com 9m de raio. O objeto pode ser guardado (em um bolso, por exemplo) para interromper a luz, que voltará a funcionar caso o objeto seja revelado. Se o alvo for um objeto em posse de uma pessoa involuntária, ela tem direito a um teste de Vontade para anular o efeito.",
    discente: "(+2 PE): muda o alcance para longo e o efeito para 4 esferas brilhantes. Cria esferas flutuantes de pura luz com 10cm de diâmetro, que você pode posicionar onde quiser dentro do alcance. Você pode enviar uma esfera à frente, outra para trás, outra para cima e manter uma perto de você, por exemplo. Uma vez por rodada, você pode mover as esferas com uma ação livre. Cada esfera ilumina uma área de 6m de raio, mas não produz calor. Se uma esfera ocupar o espaço de um ser, ele fica ofuscada e sua silhueta pode ser vista claramente (ela não recebe camuflagem por escuridão ou invisibilidade). Requer 2º círculo.",
    verdadeiro: "(+5 PE): a luz é cálida como a do sol. Dentro da área seus aliados recebem +1d20 em testes de Vontade, e seus inimigos ficam ofuscados. Requer 3º círculo.",
  ),
  Ritual(
    nome: "Nuvem de Cinzas",
    elemento: "Morte",
    circulo: 1,
    execucao: "Padrão",
    alcance: "Curto",
    alvoAreaEfeito: "Efeito: Nuvem com 6m de raio e 6m de altura",
    duracao: "Cena",
    descricao: "Uma nuvem de fuligem espessa eleva-se de um ponto a sua escolha, obscurecendo toda a visão — seres a até 1,5m têm camuflagem leve e seres a partir de 3m têm camuflagem total. Um vento forte dispersa a nuvem em 4 rodadas e um vendaval a dispersa em 1 rodada. A nuvem não funciona sob a água.",
    discente: "(+2 PE): você pode escolher seres no alcance ao conjurar o ritual; eles enxergam através do efeito. Requer 2º círculo.",
    verdadeiro: "(+5 PE): além do normal, a nuvem fica espessa, quase sólida. Qualquer ser dentro dela tem seu deslocamento reduzido para 3m (independente de seu deslocamento normal) e sofre –2 em testes de ataque. Requer 3º círculo.",
  ),
  Ritual(
    nome: "Ódio Incontrolável",
    elemento: "Sangue",
    circulo: 1,
    execucao: "Padrão",
    alcance: "Toque",
    alvoAreaEfeito: "Alvo: 1 pessoa",
    duracao: "Cena",
    descricao: "O alvo entra em um frenesi, aumentando sua agressividade e capacidade de luta. Ele recebe +2 em testes de ataque e rolagens de dano corpo a corpo e resistência a balístico, corte, impacto e perfuração 5. Enquanto o efeito durar, o alvo não pode fazer nenhuma ação que exige calma e concentração (como usar a perícia Furtividade ou conjurar rituais), e deve sempre atacar um alvo em sua rodada, mesmo que seja um aliado se ele for o único a seu alcance.",
    discente: "(+2 PE): além do normal, sempre que o alvo usar a ação agredir, pode fazer um ataque corpo a corpo adicional contra o mesmo alvo.",
    verdadeiro: "(+5 PE): muda o bônus de ataque e dano para +5 e o alvo passa a sofrer apenas metade do dano dos tipos balístico, corte, impacto e perfuração. Requer 3º círculo e afinidade.",
  ),
  Ritual(
    nome: "Ouvir os Sussurros",
    elemento: "Conhecimento",
    circulo: 1,
    execucao: "Completa",
    alcance: "Pessoal",
    alvoAreaEfeito: "Alvo: Você",
    duracao: "Instantânea",
    descricao: "O ritual conecta você com os sussurros, memórias ecoadas pelo Outro Lado, que você pode consultar para receber conhecimento proibido em relação a uma ação que tomará em breve. Ao usar este ritual, faça uma pergunta sobre um evento que você está prestes a fazer (na mesma cena) que possa ser respondida com “sim” ou “não”. O mestre rola 1d6 em segredo; com um resultado de 2 a 6, o ritual funciona e você recebe sua resposta, que pode ser “sim”, “não” ou “sim e não”. Com um resultado 1, o ritual falha e oferece o resultado “não”. Não há como saber se esse resultado foi dado porque o ritual falhou ou não. Lançar este ritual múltiplas vezes sobre o mesmo assunto gera sempre o primeiro resultado.",
    discente: "(+2 PE): muda a execução para 1 minuto. Em vez do normal, você pode consultar os ecos fazendo uma pergunta sobre um evento que poderá acontecer até um dia no futuro. O mestre rola a chance de falha; com um resultado de 2 a 6, você recebe uma resposta, desde uma simples frase até uma profecia ou enigma. Em geral, este uso oferece pistas, indicando um caminho a tomar para descobrir a resposta que se procura. Numa falha você não recebe resposta alguma. Requer 2º círculo.",
    verdadeiro: "(+5 PE): muda a execution para 10 minutos e a duração para 5 rodadas. Em vez do normal, você consulta os ecos, podendo fazer uma pergunta por rodada, desde que ela possa ser respondida com “sim”, “não” ou “ninguém sabe”. O mestre rola a chance de falha para cada pergunta. Em caso de falha, a resposta também é “ninguém sabe”. Requer 3º círculo.",
  ),
  Ritual(
    nome: "Perturbação",
    elemento: "Conhecimento",
    circulo: 1,
    execucao: "Padrão",
    alcance: "Curto",
    alvoAreaEfeito: "Alvo: 1 pessoa",
    duracao: "1 rodada",
    resistencia: "Vontade anula",
    descricao: "Você dá uma ordem que o alvo deve ser capaz de ouvir (mas não precisa entender). Se falhar na resistência, ele deve obedecer à ordem em seu próprio turno da melhor maneira possível. Escolha um dos efeitos.\n\nFuja: O alvo gasta seu turno tentando se afastar de você (usando todas as suas ações).\nLargue: O alvo solta quaisquer itens que esteja segurando e não pode pegá-los de volta até o início de seu próximo turno. Como esta é uma ação livre, ele ainda pode executar outras ações (exceto pegar aquilo que largou).\nPare: O alvo fica pasmo (não pode realizar ações, só reações).\nSente-se: Com uma ação livre, o alvo se senta no chão (se estava pendurado ou voando, desce até o chão). Ele pode fazer outras ações, mas não se levantar até o início de seu próximo turno.\nVenha: O alvo gasta seu turno se aproximando de você (usando todas as suas ações).",
    discente: "(+2 PE): muda o alvo para “1 ser” e adiciona o seguinte comando: “Sofra. O alvo é acometido de dor aguda. Ele sofre 3d8 pontos de dano de Conhecimento e fica abalado por uma rodada”.",
    verdadeiro: "(+5 PE): muda o alvo para “até 5 seres” ou adiciona o seguinte comando: “Ataque. O alvo deve fazer a ação agredir contra um outro alvo a sua escolha em alcance médio, com todas as suas capacidades”. Requer 3º círculo e afinidade.",
  ),
  Ritual(
    nome: "Polarização Caótica",
    elemento: "Energia",
    circulo: 1,
    execucao: "Padrão",
    alcance: "Curto",
    alvoAreaEfeito: "Alvo: Você",
    duracao: "Sustentada",
    resistencia: "Vontade anula",
    descricao: "Você gera uma aura magnética sobrenatural. Escolha um dos efeitos a seguir.\n\nAtrair: você pode usar uma ação de movimento para puxar um objeto metálico de espaço 2 ou menor dentro do alcance. Se o objeto estiver livre, voa para suas mãos (caso tenha mãos livres para apanhá-lo) ou para seus pés.\nRepelir: você repele objetos de espaço 2 ou menor (o que envolve quase todos os projéteis e armas de arremesso), recebendo resistência a balístico, corte, impacto e perfuração 5.",
    discente: "(+2 PE): muda a duração para instantânea. nesta versão a energia magnética é expelida de uma única vez e arremessa até 10 objetos, ou um total de 10 espaços, o que for menor. Os objetos devem estar a até 3m uns dos outros. Objetos arremessados podem atingir seres em seu caminho, causando de 1 ponto de dano de impacto por espaço (objetos macios, sem pontas ou sem fio) até 1d6 pontos de dano por espaço (objetos duros, pontudos ou afiados). Seres atingidos têm direito a um teste de Reflexos para reduzir o dano à metade. Seres dentro da capacidade de carga do efeito podem ser arremessados, mas têm direito a um teste de Vontade para evitar o efeito (em si mesmos ou em objetos que estejam segurando). Um ser arremessado contra uma superfície sólida sofre 1d6 pontos de dano de impacto para cada 3m que “voou” no deslocamento (incluindo outros seres; nesse caso, ambos sofrem o dano).",
    verdadeiro: "(+5 PE): muda o alcance para médio e a duração para instantânea. Você pode usar uma ação de movimento para fazer com que a força magnética levite e mova um ser ou objeto de espaço 10 ou menor por até 9m em qualquer direção dentro do alcance. Um ser pode anular o efeito sobre ele, ou sobre um objeto que possua, passando num teste de Vontade. O alvo cai no chão se sair do alcance ou o efeito terminar.",
  ),
  Ritual(
    nome: "Tecer Ilusão",
    elemento: "Conhecimento",
    circulo: 1,
    execucao: "Padrão",
    alcance: "Médio",
    alvoAreaEfeito: "Efeito: Ilusão que se estende a até 4 cubos de 1,5m",
    duracao: "Cena",
    resistencia: "Vontade desacredita",
    descricao: "Este ritual cria uma ilusão visual (uma pessoa, uma parede…) ou sonora (um grito de socorro, um uivo assustador…). O ritual cria apenas imagens ou sons simples, com volume equivalente à voz de uma pessoa para cada cubo de 1,5m no efeito. Não é possível criar cheiros, texturas ou temperaturas, nem sons complexos, como uma música ou diálogo. Seres e objetos atravessam uma ilusão sem sofrer dano, mas o ritual pode, por exemplo, esconder uma armadilha ou emboscada. A ilusão é dissipada se você sair do alcance.",
    discente: "(+2 PE): muda o efeito para até 8 cubos de 1,5m e a duração para sustentada. Você pode criar ilusões de imagem e som combinados, e pode criar sons complexos, odores e sensações térmicas. Também pode criar sensações táteis, como texturas; objetos ainda atravessam a ilusão, mas seres não conseguem atravessá-la sem passar em um teste de Vontade. A cada rodada, você pode usar uma ação livre para mover a imagem ou alterar o som, como aumentar o volume ou fazer com que pareça se afastar ou se aproximar, ainda dentro dos limites do efeito. Você pode, por exemplo, criar a ilusão de um fantasma que anda pela sala, controlando seus movimentos. A ilusão ainda é incapaz de causar ou sofrer dano. Quando você para de sustentar o ritual, a imagem ou som persiste por mais uma rodada antes do ritual se dissipar. Requer 2º círculo.",
    verdadeiro: "(+ 5 PE): você cria a ilusão de um perigo mortal. Quando o ritual é conjurado, e no início de cada um de seus turnos, um alvo interagindo com a ilusão deve fazer um teste de Vontade; se falhar, acredita que a ilusão é real e sofre 6d6 pontos de dano de Conhecimento. O alvo racionaliza o efeito sempre que falha no teste (por exemplo, acredita que o mesmo teto pode cair sobre ele várias vezes). Se um alvo passar em dois testes de Vontade seguidos, o efeito é anulado para ele. Requer 3º círculo.",
  ),
  Ritual(
    nome: "Terceiro Olho",
    elemento: "Conhecimento",
    circulo: 1,
    execucao: "Padrão",
    alcance: "Pessoal",
    alvoAreaEfeito: "Alvo: Você",
    duracao: "Cena",
    descricao: "Seus olhos se enchem de sigilos e você passa a enxergar auras paranormais em alcance longo. Rituais, itens amaldiçoados e criaturas emitem auras. Você sabe o elemento da aura e seu poder aproximado — rituais de 1º círculo e criaturas de VD até 80 emitem uma aura fraca; rituais de 2º e 3º círculos e criaturas de VD entre 81 e 280 emitem uma aura moderada, e rituais de 4º círculo e criaturas de VD 281 ou maior emitem uma aura poderosa. Além disso, você pode gastar uma ação de movimento para descobrir se um ser que possa ver em alcance médio tem poderes paranormais ou se é capaz de conjurar rituais e de quais elementos.",
    discente: "(+2 PE): muda a duração para 1 dia.",
    verdadeiro: "(+5 PE): também pode enxergar objetos e seres invisíveis, que aparecem como formas translúcidas.",
  ),
  Ritual(
    nome: "Esfolar",
    elemento: "Sangue",
    circulo: 1,
    execucao: "Padrão",
    alcance: "Curto",
    alvoAreaEfeito: "Alvo: 1 ser",
    duracao: "Instantânea",
    resistencia: "Reflexos parcial",
    descricao: "Você usa seu corpo como passagem para o Sangue, projetando agulhas e lâminas rubras praticamente imperceptíveis que se projetam contra o alvo. O ser sofre 3d4+3 pontos de dano de corte e fica sangrando. Se passar no teste de resistência, sofre apenas metade do dano e evita a condição.",
    discente: "(+2 PE): muda o alcance para médio, o dano para 5d4+5 e o alvo para explosão com 6m de raio. Requer 2º círculo.",
    verdadeiro: "(+5 PE): muda o alcance para longo, o dano para 10d4+10 e o alvo para explosão com 6m de raio. Passar no teste de resistência não evita a condição. Requer 3º círculo.",
  ),
  Ritual(
    nome: "Apagar as Luzes",
    elemento: "Morte",
    circulo: 1,
    execucao: "Padrão",
    alcance: "Pessoal",
    alvoAreaEfeito: "Alvo: Você",
    duracao: "Instantânea",
    descricao: "Ao conjurar esse ritual, qualquer fonte de luz em alcance curto de você, natural ou paranormal, se apaga (criando um ambiente de penumbra ou escuridão, o que fizer mais sentido com a cena). A forma como isso acontece se assemelha às obras mais dramáticas de terror (lâmpadas estouram, janelas se fecham, nuvens densas bloqueiam a luz do sol, velas se dissipam, etc.). O efeito é instantâneo, mas no caso de eventos temporários, como nuvens cobrindo o sol em uma direção específica ou janelas que podem ser abertas, eles permanecem mantendo a escuridão, pelo menos, até o fim da cena (o vento não move a nuvem e a janela fica sobrenaturalmente impossível de ser aberta). Você, por outro lado, recebe visão no escuro, até o fim da cena.",
    discente: "(+2 PE): muda o alcance para determinar fontes de luz afetadas para longo. Requer 2º círculo.",
    verdadeiro: "(+5 PE): como Discente, e além de você, até cinco outros seres dentro desse alcance recebem visão no escuro. Requer 3º círculo.",
  ),
  Ritual(
    nome: "Desfazer Sinapses",
    elemento: "Conhecimento",
    circulo: 1,
    execucao: "Padrão",
    alcance: "Curto",
    alvoAreaEfeito: "Alvo: 1 ser",
    duracao: "Instantânea",
    resistencia: "Vontade parcial",
    descricao: "A entidade do Conhecimento inexiste bilhões de neurônios de dentro do cérebro do alvo, causando a angústia inexplicável do vazio. O alvo sofre 2d6+2 pontos de dano de Conhecimento e fica frustrado por uma rodada. Se passar no teste de resistência, sofre apenas metade do dano e evita a condição. O alvo precisa ter um cérebro; o efeito se reflete como uma dor de cabeça severa que faz sangrar levemente pelos olhos, narinas, orelhas e boca.",
    discente: "(+2 PE): muda o alcance para longo, o dano para 3d6+3 e o alvo para até 5 seres a sua escolha. Requer 2º círculo.",
    verdadeiro: "(+5 PE): muda o alcance para extremo, o dano para 8d6+8 e a condição para esmorecido. Se passar no teste de resistência, em vez de esmorecido, fica frustrado. Requer 3º círculo.",
  ),
  Ritual(
    nome: "Overclock",
    elemento: "Energia",
    circulo: 1,
    execucao: "Reação",
    alcance: "Pessoal",
    alvoAreaEfeito: "Alvo: Você",
    duracao: "Instantânea",
    descricao: "Ao fazer um teste de Tecnologia para lidar com um objeto eletrônico, você pode, após saber se passou no teste ou não, conjurar este ritual para receber as informações que buscava de outra forma, usando descargas de Energia para forçar o aparelho a seguir suas vontades. Esta outra forma precisa que o mestre tenha acesso a uma música, pois o jogador será desafiado em um jogo de “estátua” (enquanto a música durar você deve mover os dedos no ar, mas quando o mestre interrompê-la, deve ficar imóvel). O mínimo movimento errado resulta em falha. Se não falhar até o fim da música, descobre o que queria do aparelho. Contudo, após isso, o objeto é tomado por flickering e chiados, tornando seu uso impossível, como se atacado por um vírus paranormal.",
    discente: "(+2 PE): você só falha no teste se errar duas vezes no jogo de estátua. Requer 2º círculo.",
    verdadeiro: "(+5 PE): você só falha no teste se errar três vezes no jogo de estátua. Requer 3º círculo.",
  ),

  // ==========================================
  // RITUAIS DE 2º CÍRCULO
  // ==========================================
  Ritual(
    nome: "Aprimorar Físico",
    elemento: "Sangue",
    circulo: 2,
    execucao: "Padrão",
    alcance: "Toque",
    alvoAreaEfeito: "Alvo: 1 ser",
    duracao: "Cena",
    custoPE: 3,
    descricao: "O alvo tem seus músculos tonificados e seus ligamentos reforçados, recebendo +1 em Agilidade ou Força, à escolha dele.",
    discente: "(+3 PE): muda o bônus para +2. Requer 3º círculo.",
    verdadeiro: "(+7 PE): muda o bônus para +3. Requer 4º círculo e afinidade.",
  ),
  Ritual(
    nome: "Aprimorar Mente",
    elemento: "Conhecimento",
    circulo: 2,
    execucao: "Padrão",
    alcance: "Toque",
    alvoAreaEfeito: "Alvo: 1 ser",
    duracao: "Cena",
    custoPE: 3,
    descricao: "O alvo tem sua mente energizada por fagulhos do Conhecimento. Ele recebe +1 em Intelecto ou Presença, à escolha dele (PE, perícias treinadas ou graus de treinamento).",
    discente: "(+3 PE): muda o bônus para +2. Requer 3º círculo.",
    verdadeiro: "(+7 PE): muda o bônus para +3. Requer 4º círculo e afinidade.",
  ),
  Ritual(
    nome: "Chamas do Caos",
    elemento: "Energia",
    circulo: 2,
    execucao: "Padrão",
    alcance: "Curto",
    alvoAreaEfeito: "Alvo: veja texto",
    duracao: "Cena",
    custoPE: 3,
    descricao: "Você manipula o calor e o fogo. Escolha um:\nChamejar: O alvo (arma corpo a corpo) causa +1d6 de fogo.\nEsquentar: O alvo (objeto) sofre 1d6 de fogo por rodada e queima quem o segura. Um ser pode gastar ação completa para resfriar.\nExtinguir: Apaga uma chama Grande ou menor, criando fumaça de 3m (camuflagem leve).\nModelar: A cada rodada (ação livre), move uma chama Grande ou menor em 9m. Se passar por um ser, causa 3d6 de fogo (uma vez por rodada).",
    discente: "(+3 PE): muda duração para sustentada. Adiciona 'Resistência: Reflexos reduz à metade'. Em vez do normal, você projeta uma labareda (ação de movimento) em alcance curto que causa 4d6 de Energia.",
    verdadeiro: "(+ 7 PE): como discente, mas muda o dano para 8d6. Requer 3º círculo.",
  ),
  Ritual(
    nome: "Contenção Fantasmagórica",
    elemento: "Energia",
    circulo: 2,
    execucao: "Padrão",
    alcance: "Médio",
    alvoAreaEfeito: "Alvo: 1 ser",
    duracao: "Cena",
    custoPE: 3,
    resistencia: "Reflexos anula",
    descricao: "Três laços de Energia agarram o alvo. O alvo pode usar ação padrão (teste de Atletismo x DT do ritual) para destruir um laço, mais um a cada 5 pontos acima da DT. Cada laço tem Defesa 10, 10 PV, RD 5 e imunidade a Energia. Afeta incorpóreos.",
    discente: "(+3 PE): aumenta para 6 laços. Você pode dividir entre vários alvos (mín. 2 laços por alvo). Requer 3º círculo.",
    verdadeiro: "(+5 PE): como discente, e cada laço destruído libera 2d6+2 de dano de Energia no alvo agarrado. Requer 3º círculo e afinidade.",
  ),
  Ritual(
    nome: "Desacelerar Impacto",
    elemento: "Morte",
    circulo: 2,
    execucao: "Reação",
    alcance: "Curto",
    alvoAreaEfeito: "Alvos: 1 ser ou objetos (até 10 espaços)",
    duracao: "Até chegar ao solo ou cena",
    custoPE: 3,
    descricao: "O alvo cai lentamente (18m/rodada), o suficiente para não sofrer dano de queda. Se usado num projétil em queda livre, reduz o dano dele pela metade. Não funciona contra ataques diretos ou mergulhos intencionais.",
    verdadeiro: "(+3 PE): aumenta o total de alvos para seres ou objetos somando até 100 espaços.",
  ),
  Ritual(
    nome: "Descarnar",
    elemento: "Sangue",
    circulo: 2,
    execucao: "Padrão",
    alcance: "Toque",
    alvoAreaEfeito: "Alvo: 1 ser",
    duracao: "Instantânea",
    custoPE: 3,
    resistencia: "Fortitude parcial",
    descricao: "Causa 6d8 de dano (metade corte/metade Sangue) e hemorragia severa. O alvo faz um teste de Fortitude no início de seus turnos; se falhar, sofre 2d8 de Sangue. Dois sucessos seguidos estancam a hemorragia. Se passar na resistência inicial, sofre metade e não sangra.",
    discente: "(+3 PE): muda o dano direto para 10d8 e a hemorragia para 4d8. Requer 3º círculo.",
    verdadeiro: "(+7 PE): muda o alvo para você e duração para sustentada. Seus ataques corpo a corpo causam +4d8 de Sangue e deixam o alvo com hemorragia. Requer 3º círculo e afinidade.",
  ),
  Ritual(
    nome: "Detecção de Ameaças",
    elemento: "Conhecimento",
    circulo: 2,
    execucao: "Padrão",
    alcance: "Pessoal",
    alvoAreaEfeito: "Área: Esfera de 18m",
    duracao: "Cena",
    custoPE: 3,
    descricao: "Você sente perigos à sua volta. Se algo hostil entrar na área, você pode gastar ação de movimento para testar Percepção (DT 20). Se passar, descobre direção e distância.",
    discente: "(+3 PE): você não fica desprevenido contra perigos detectados e recebe +5 em resistências contra armadilhas. Requer 3º círculo.",
    verdadeiro: "(+5 PE): muda duração para 1 dia e mantém benefícios de discente. Requer 4º círculo.",
  ),
  Ritual(
    nome: "Dissonância Acústica",
    elemento: "Energia",
    circulo: 2,
    execucao: "Padrão",
    alcance: "Médio",
    alvoAreaEfeito: "Área: Esfera com 6m de raio",
    duracao: "Sustentada",
    custoPE: 3,
    descricao: "Todos os seres na área ficam surdos. A dissonância impede conjuração de rituais.",
    discente: "(+1 PE): muda a área para alvo (1 objeto). O objeto emana silêncio em 3m de raio. Seres involuntários com o objeto testam Vontade para anular.",
    verdadeiro: "(+3 PE): muda duração para cena. Nenhum som sai da área, mas quem está dentro pode falar e conjurar normalmente. Requer 3º círculo.",
  ),
  Ritual(
    nome: "Eco Espiral",
    elemento: "Morte",
    circulo: 2,
    execucao: "Padrão",
    alcance: "Curto",
    alvoAreaEfeito: "Alvo: 1 ser",
    duracao: "2 rodadas",
    custoPE: 3,
    resistencia: "Fortitude reduz à metade",
    descricao: "Você cria uma cópia de cinzas do alvo. No 1º turno seguinte, gasta ação padrão para concentrar (ou dissipa). No 2º turno, gasta ação padrão para descarregar. A cópia explode e causa dano de Morte igual ao dano que o alvo sofreu durante o turno de concentração.",
    discente: "(+3 PE): muda o alvo para até 5 seres.",
    verdadeiro: "(+7 PE): muda duração para até 3 rodadas, permitindo concentrar por 2 rodadas e descarregar na 3ª. Requer 4º círculo e afinidade.",
  ),
  Ritual(
    nome: "Esconder dos Olhos",
    elemento: "Conhecimento",
    circulo: 2,
    execucao: "Livre",
    alcance: "Pessoal",
    alvoAreaEfeito: "Alvo: Você",
    duracao: "1 rodada",
    custoPE: 3,
    descricao: "Você e seu equipamento ficam invisíveis (+15 Furtividade, camuflagem total, inimigos desprevenidos). O efeito termina se fizer ação hostil. Causar dano indireto (armar bombas) não quebra a invisibilidade. Luz não fica invisível.",
    discente: "(+3 PE): muda para sustentada. Cria esfera de 3m que torna você e aliados invisíveis (ações hostis quebram individualmente). A esfera te acompanha. Requer 3º círculo.",
    verdadeiro: "(+7 PE): muda execução para padrão, alcance para toque, alvo para 1 ser, duração para sustentada. O efeito NÃO é quebrado por ação hostil. Requer 4º círculo e afinidade.",
  ),
  Ritual(
    nome: "Flagelo de Sangue",
    elemento: "Sangue",
    circulo: 2,
    execucao: "Padrão",
    alcance: "Toque",
    alvoAreaEfeito: "Alvo: 1 pessoa",
    duracao: "Cena",
    custoPE: 3,
    resistencia: "Fortitude parcial",
    descricao: "Você grava uma ordem na pele do alvo ('siga-me', 'não me ataque'). A cada rodada que desobedecer, sofre 10d6 de Sangue e fica enjoado (Fortitude reduz à metade e evita condição). Se passar em 2 testes seguidos, a marca some.",
    discente: "(+3 PE): muda o alvo para 1 ser (exceto criaturas de Sangue). Requer 3º círculo.",
    verdadeiro: "(+7 PE): como Discente, e muda duração para 1 dia. Requer 4º círculo e afinidade.",
  ),
  Ritual(
    nome: "Hemofagia",
    elemento: "Sangue",
    circulo: 2,
    execucao: "Padrão",
    alcance: "Toque",
    alvoAreaEfeito: "Alvo: 1 ser",
    duracao: "Instantânea",
    custoPE: 3,
    resistencia: "Fortitude reduz à metade",
    descricao: "Causa 6d6 de Sangue. Você absorve o sangue e recupera PV iguais à metade do dano causado.",
    discente: "(+3 PE): muda resistência para 'nenhuma'. Como parte do ritual, faz um ataque corpo a corpo. Causa dano da arma + dano do ritual, curando metade do total. Requer 3º círculo.",
    verdadeiro: "(+7 PE): muda alcance/alvo para você e duração para cena. A cada rodada, com ação padrão, pode tocar 1 ser causando 4d6 de Sangue e curando metade. Requer 4º círculo.",
  ),
  Ritual(
    nome: "Invadir Mente",
    elemento: "Conhecimento",
    circulo: 2,
    execucao: "Padrão",
    alcance: "Médio ou Toque",
    alvoAreaEfeito: "Alvo: 1 ser ou 2 voluntários",
    duracao: "Instantânea ou 1 dia",
    custoPE: 3,
    resistencia: "Vontade parcial ou nenhuma",
    descricao: "Escolha:\nRajada Mental: 6d6 de Conhecimento e atordoado (Vontade reduz dano e evita atordoamento). Um alvo só é atordoado 1x por cena.\nLigação Telepática: Elo mental entre 2 pessoas (1 dia) para comunicação.",
    discente: "(+3 PE): Rajada causa 10d6. Ligação permite gastar ação de movimento para ver/ouvir pelos sentidos do alvo (involuntários testam Vontade para bloquear por 1 hora). Requer 3º círculo.",
    verdadeiro: "(+7 PE): Rajada causa 10d6 em múltiplos alvos escolhidos. Ligação vincula até 5 pessoas. Requer 4º círculo.",
  ),
  Ritual(
    nome: "Localização",
    elemento: "Conhecimento",
    circulo: 2,
    execucao: "Padrão",
    alcance: "Pessoal",
    alvoAreaEfeito: "Área: Círculo de 90m",
    duracao: "Cena",
    custoPE: 3,
    descricao: "Encontra a direção/distância de pessoa ou objeto no alcance. Pode ser geral ('um policial') ou específico (exige imagem mental precisa). É bloqueado por chumbo.",
    discente: "(+3 PE): muda para toque, 1 pessoa e 1 hora. A pessoa descobre a rota mais direta para entrar/sair de um local geográfico (não acha objetos). Se demorar > 1 hora, perde-se a rota.",
    verdadeiro: "(+7 PE): aumenta a área para 1km. Requer 4º círculo.",
  ),
  Ritual(
    nome: "Miasma Entrópico",
    elemento: "Morte",
    circulo: 2,
    execucao: "Padrão",
    alcance: "Médio",
    alvoAreaEfeito: "Área: Nuvem com 6m de raio",
    duracao: "Instantânea",
    custoPE: 3,
    resistencia: "Fortitude parcial",
    descricao: "Explosão tóxica. Causa 4d8 de dano Químico e enjoo por 1 rodada. (Fortitude reduz metade e evita enjoo).",
    discente: "(+3 PE): muda o dano para 6d8 de Morte.",
    verdadeiro: "(+7 PE): como discente, mas muda duração para 3 rodadas. Seres iniciados na área sofrem dano novamente. Requer 3º círculo.",
  ),
  Ritual(
    nome: "Paradoxo",
    elemento: "Morte",
    circulo: 2,
    execucao: "Padrão",
    alcance: "Médio",
    alvoAreaEfeito: "Área: Esfera com 6m de raio",
    duracao: "Instantânea",
    custoPE: 3,
    resistencia: "Fortitude reduz à metade",
    descricao: "Implosão de distorção temporal causa 6d6 de Morte na área.",
    discente: "(+3 PE): muda área para 1,5m e duração para cena. Cria esfera voadora de 1,5m que causa 4d6 de Morte a quem dividir espaço. Pode ser movida 9m/rodada com ação de movimento.",
    verdadeiro: "(+7 PE): muda dano para 13d6. Seres zerados pelo dano testam Fortitude; se falharem, viram cinzas. Requer 4º círculo.",
  ),
  Ritual(
    nome: "Proteção contra Rituais",
    elemento: "Medo",
    circulo: 2,
    execucao: "Padrão",
    alcance: "Toque",
    alvoAreaEfeito: "Alvo: 1 ser",
    duracao: "Cena",
    custoPE: 3,
    descricao: "O alvo recebe RD Paranormal 5 e +5 em testes de resistência contra efeitos/rituais paranormais.",
    discente: "(+3 PE): afeta até 5 seres tocados. Requer 3º círculo.",
    verdadeiro: "(+6 PE): afeta 5 seres, RD sobe para 10 e bônus de resistência para +10. Requer 4º círculo.",
  ),
  Ritual(
    nome: "Rejeitar Névoa",
    elemento: "Medo",
    circulo: 2,
    execucao: "Padrão",
    alcance: "Curto",
    alvoAreaEfeito: "Área: Nuvem com 6m de raio",
    duracao: "Cena",
    custoPE: 3,
    descricao: "Rituais conjurados na área custam +2 PE por círculo e execução sobe em um passo. Anula Cinerária, a menos que o conjurador da Cinerária gaste ação completa todo turno para empatar.",
    discente: "(+2 PE): DTs contra rituais na área caem em -5.",
    verdadeiro: "(+5 PE): dano causado por rituais na névoa é sempre mínimo.",
  ),
  Ritual(
    nome: "Sopro do Caos",
    elemento: "Energia",
    circulo: 2,
    execucao: "Padrão",
    alcance: "Médio",
    alvoAreaEfeito: "Área: Varia",
    duracao: "Sustentada",
    custoPE: 3,
    descricao: "Escolha:\nAscender: Levita (ação de movimento) alvo Médio até 30m de altura (vulnerável). Se soltar, sofre dano de queda. Pode ser usado para Derrubar voadores (Ocultismo x Luta).\nSopro: Lufada num cone de 4,5m. Faz manobra Empurrar (Ocultismo x Luta) em todos. Exige ação padrão para manter.\nVento: Cria ou amplifica vento forte na área. Exige ação de movimento.",
    discente: "(+3 PE): afeta alvos Grandes.",
    verdadeiro: "(+9 PE): afeta alvos Enormes.",
  ),
  Ritual(
    nome: "Tela de Ruído",
    elemento: "Energia",
    circulo: 2,
    execucao: "Padrão (ou Reação)",
    alcance: "Pessoal",
    alvoAreaEfeito: "Alvo: Você",
    duracao: "Cena (ou Instantânea)",
    custoPE: 3,
    descricao: "Como Padrão: Recebe 30 PV temporários (só contra balístico, corte, impacto, perfuração).\nComo Reação: Conjura ao sofrer dano para receber RD 15 apenas contra o gatilho.",
    discente: "(+3 PE): PV temp sobe para 60 e RD da Reação sobe para 30.",
    verdadeiro: "(+7 PE): muda alcance/alvo para ser/objeto Enorme. Cria esfera-prisão intransponível ao redor do alvo (Reflexos evita). Requer 4º círculo.",
  ),
  Ritual(
    nome: "Transfusão Vital",
    elemento: "Sangue",
    circulo: 2,
    execucao: "Padrão",
    alcance: "Toque",
    alvoAreaEfeito: "Alvo: 1 ser",
    duracao: "Instantânea",
    custoPE: 3,
    descricao: "Você transfere até 30 PV seus para o alvo. Seu limite mínimo após transferência é 1 PV.",
    discente: "(+3 PE): Pode transferir até 50 PV. Requer 3º círculo.",
    verdadeiro: "(+7 PE): Pode transferir até 100 PV. Requer 4º círculo.",
  ),
  Ritual(
    nome: "Velocidade Mortal",
    elemento: "Morte",
    circulo: 2,
    execucao: "Padrão",
    alcance: "Curto",
    alvoAreaEfeito: "Alvo: 1 ser",
    duracao: "Sustentada",
    custoPE: 3,
    descricao: "O alvo recebe uma ação de movimento adicional por turno (não pode ser usada para conjurar).",
    discente: "(+3 PE): o alvo recebe uma ação padrão extra em vez de movimento.",
    verdadeiro: "(+7 PE): afeta múltiplos alvos escolhidos. Requer 4º círculo e afinidade.",
  ),
  Ritual(
    nome: "Sede de Adrenalina",
    elemento: "Sangue",
    circulo: 2,
    execucao: "Reação",
    alcance: "Pessoal",
    alvoAreaEfeito: "Alvo: Você",
    duracao: "Instantânea",
    custoPE: 3,
    descricao: "Ao falhar em Acrobacia ou Atletismo, repete o teste usando Presença. OU, ao sofrer dano de Impacto, reduz em 20. Se usado para reduzir dano, sofre atordoamento (1 rodada) após o hit. Limite 1x/rodada.",
    discente: "(+3 PE): a RD de impacto sobe para 40.",
    verdadeiro: "(+7 PE): a RD de impacto sobe para 70. Requer 4º círculo e afinidade.",
  ),
  Ritual(
    nome: "Língua Morta",
    elemento: "Morte",
    circulo: 2,
    execucao: "Padrão",
    alcance: "Toque",
    alvoAreaEfeito: "Alvo: 1 cadáver",
    duracao: "Sustentada",
    custoPE: 3,
    descricao: "Reanima o cadáver com Lodo, permitindo 1 pergunta/rodada até max de 3. Ao fim da 3ª, o corpo vira um esqueleto de Lodo inimigo. O mestre dita a clareza baseada no estado do corpo.",
    discente: "(+3 PE): limite sobe para 4 rodadas. No fim vira um enraizado.",
    verdadeiro: "(+7 PE): limite sobe para 5 rodadas. No fim vira uma marionete. Requer 4º círculo e afinidade.",
  ),
  Ritual(
    nome: "Aurora da Verdade",
    elemento: "Conhecimento",
    circulo: 2,
    execucao: "Padrão",
    alcance: "Curto",
    alvoAreaEfeito: "Área: Esfera de 3m",
    duracao: "Sustentada",
    custoPE: 3,
    resistencia: "Vontade parcial",
    descricao: "Obriga todos na área a falarem a verdade (Vontade permite mentir). Além disso, cancela camuflagem e invisibilidade, iluminando os seres ocultos com sigilos.",
    discente: "(+3 PE): muda para médio/9m. O conjurador não é mais afetado pela restrição de verdade.",
    verdadeiro: "(+7 PE): muda para longo/cena. O conjurador ouve tudo falado na área, não importa quão longe vá. Requer 4º círculo e afinidade.",
  ),
  Ritual(
    nome: "Tremeluzir",
    elemento: "Energia",
    circulo: 2,
    execucao: "Padrão",
    alcance: "Pessoal",
    alvoAreaEfeito: "Alvo: Você",
    duracao: "Sustentada",
    custoPE: 3,
    descricao: "Você deforma-se em fótons e pode atravessar matéria. Você NÃO fica incorpóreo a danos, e atravessar um objeto custa ação de movimento (25% chance de falha). Permite 'cortar caminho' sem penalidade em perseguições. Causa 1d4 de Energia que ignora RD a cada rodada ativa. Se acabar o turno dentro de matéria, sofre +1d4.",
    discente: "(+3 PE): muda alcance para Toque / 1 alvo voluntário.",
    verdadeiro: "(+7 PE): afeta até 5 seres voluntários em alcance curto. Requer 4º círculo.",
  ),

  // ==========================================
  // RITUAIS DE 3º CÍRCULO
  // ==========================================
  Ritual(
    nome: "Alterar Memória",
    elemento: "Conhecimento",
    circulo: 3,
    execucao: "Padrão",
    alcance: "Toque",
    alvoAreaEfeito: "Alvo: 1 pessoa",
    duracao: "Instantânea",
    custoPE: 6,
    resistencia: "Vontade anula",
    descricao: "Você invade a mente do alvo e altera ou apaga suas memórias de até uma hora atrás. Se escolher alterar, pode mudar detalhes (como a identidade de alguém ou endereço), mas não reescrever o evento inteiro. O alvo recupera a memória após 1d4 dias.",
    verdadeiro: "(+4 PE): pode alterar ou apagar memórias de até 24 horas atrás. Requer 4º círculo.",
  ),
  Ritual(
    nome: "Âncora Temporal",
    elemento: "Morte",
    circulo: 3,
    execucao: "Padrão",
    alcance: "Curto",
    alvoAreaEfeito: "Alvo: 1 ser",
    duracao: "Cena",
    custoPE: 6,
    resistencia: "Vontade parcial",
    descricao: "Uma aura espiralada surge no alvo. No início do turno dele, deve testar Vontade. Se falhar, não pode se deslocar naquele turno (ainda pode agir). Se passar dois turnos seguidos, o efeito termina.",
    verdadeiro: "(+4 PE): muda o alvo para “seres a sua escolha”. Requer 4º círculo.",
  ),
  Ritual(
    nome: "Contato Paranormal",
    elemento: "Conhecimento",
    circulo: 3,
    execucao: "Completa",
    alcance: "Pessoal",
    alvoAreaEfeito: "Alvo: Você",
    duracao: "1 dia",
    custoPE: 6,
    descricao: "Você recebe seis d6 de auxílio. Ao testar uma perícia, pode gastar um d6 e somar ao resultado. Preço: se rolar um 6 no dado de auxílio, você perde 2 de Sanidade. O ritual acaba se ficar sem dados ou chegar a 0 SAN.",
    discente: "(+4 PE): muda os dados para d8. Rolar um 8 consome 3 de SAN. Requer 4º círculo.",
    verdadeiro: "(+9 PE): muda os dados para d12. Rolar um 12 consome 5 de SAN. Requer 4º círculo e afinidade.",
  ),
  Ritual(
    nome: "Convocação Instantânea",
    elemento: "Energia",
    circulo: 3,
    execucao: "Padrão",
    alcance: "Ilimitado",
    alvoAreaEfeito: "Alvo: 1 objeto (até 2 espaços)",
    duracao: "Instantânea",
    custoPE: 6,
    resistencia: "Vontade anula",
    descricao: "Invoca para sua mão um objeto previamente marcado com o sigilo. Se estiver com outra pessoa, ela testa Vontade para negar (você ainda descobre quem/onde está). Você tem até 1h para devolver o objeto ao lugar original com ação de movimento.",
    discente: "(+4 PE): muda o alvo para objeto de até 10 espaços.",
    verdadeiro: "(+9 PE): muda alvo para '1 recipiente Médio' (somando até 10 espaços) e duração para permanente. Você encanta o recipiente inteiro.",
  ),
  Ritual(
    nome: "Dissipar Ritual",
    elemento: "Medo",
    circulo: 3,
    execucao: "Padrão",
    alcance: "Médio",
    alvoAreaEfeito: "1 ser, objeto ou esfera (3m raio)",
    duracao: "Instantânea",
    custoPE: 6,
    descricao: "Anula rituais ativos na área com DT menor ou igual a um teste de Ocultismo que você fizer (não afeta rituais de duração instantânea). Pode anular poderes de um item amaldiçoado por 1 dia (se empunhado, usuário testa Vontade para negar).",
  ),
  Ritual(
    nome: "Ferver Sangue",
    elemento: "Sangue",
    circulo: 3,
    execucao: "Padrão",
    alcance: "Curto",
    alvoAreaEfeito: "Alvo: 1 ser",
    duracao: "Sustentada",
    custoPE: 6,
    resistencia: "Fortitude parcial",
    descricao: "No início de cada turno do alvo, ele testa Fortitude. Falha: 4d8 de Sangue e fica fraco. Sucesso: Metade do dano e não fica fraco na rodada. O efeito termina se ele passar em dois turnos seguidos.",
    verdadeiro: "(+4 PE): afeta seres escolhidos. Requer 4º círculo e afinidade.",
  ),
  Ritual(
    nome: "Forma Monstruosa",
    elemento: "Sangue",
    circulo: 3,
    execucao: "Padrão",
    alcance: "Pessoal",
    alvoAreaEfeito: "Alvo: Você",
    duracao: "Cena",
    custoPE: 6,
    descricao: "Seu tamanho vira Grande. Roupas e armas fundem-se ao corpo virando garras/couraça. Recebe +5 em ataque/dano corpo a corpo e 30 PV temp. Fica furioso: não pode falar ou conjurar. Todo turno DEVE atacar/ir em direção ao ser mais próximo. Se for um aliado, teste de Vontade vs DT do ritual para poder escolher o alvo.",
    discente: "(+3 PE): recebe imunidade a atordoamento, fadiga, sangramento, sono e veneno.",
    verdadeiro: "(+9 PE): muda os bônus de ataque/dano para +10 e os PV temp para 50. Requer 4º círculo e afinidade.",
  ),
  Ritual(
    nome: "Mergulho Mental",
    elemento: "Conhecimento",
    circulo: 3,
    execucao: "Padrão",
    alcance: "Toque",
    alvoAreaEfeito: "Alvo: 1 pessoa",
    duracao: "Sustentada",
    custoPE: 6,
    resistencia: "Vontade parcial",
    descricao: "Durante o mergulho você fica desprevenido. No início de seu turno (enquanto tocar/sustentar), o alvo testa Vontade. Se falhar, deve responder 'sim/não' a uma pergunta sua (sem poder mentir).",
    verdadeiro: "(+4 PE): execução 1 dia, alcance ilimitado (exige componente: máscara e cuba de ouro d'água). Mergulha à distância se tiver nome e pertence/foto do alvo. Requer 4º círculo.",
  ),
  Ritual(
    nome: "Poeira da Podridão",
    elemento: "Morte",
    circulo: 3,
    execucao: "Padrão",
    alcance: "Médio",
    alvoAreaEfeito: "Área: Nuvem com 6m de raio",
    duracao: "Sustentada",
    custoPE: 6,
    resistencia: "Fortitude",
    descricao: "Nuvem necrosante. Seres/objetos na área sofrem 4d8 de Morte no momento e no início dos seus turnos (Fortitude reduz metade). Falhar na Fortitude também impede curar PV por 1 rodada.",
    verdadeiro: "(+4 PE): muda o dano para 4d8+16.",
  ),
  Ritual(
    nome: "Purgatório",
    elemento: "Sangue",
    circulo: 3,
    execucao: "Padrão",
    alcance: "Curto",
    alvoAreaEfeito: "Área: 6m de raio",
    duracao: "Sustentada",
    custoPE: 6,
    resistencia: "Fortitude parcial",
    descricao: "Inimigos na poça de sangue ficam vulneráveis a dano Físico (Balístico, Corte, Impacto, Perfuração). Tentar sair causa 6d6 de Sangue e teste de Fortitude (falha: perde ação de movimento e fica preso).",
  ),
  Ritual(
    nome: "Salto Fantasma",
    elemento: "Energia",
    circulo: 3,
    execucao: "Padrão",
    alcance: "Médio",
    alvoAreaEfeito: "Alvo: Você",
    duracao: "Instantânea",
    custoPE: 6,
    descricao: "Viaja em forma de Energia até um local imaginado no alcance (exige conhecimento prévio do local). Não pode agir no resto do turno. Não surge dentro de objetos.",
    discente: "(+2 PE): execução vira Reação. Salta 1,5m e recebe +10 Defesa/Reflexos contra 1 ataque iminente.",
    verdadeiro: "(+4 PE): alcance Longo. Pode levar até 2 voluntários tocados.",
  ),
  Ritual(
    nome: "Tentáculos de Lodo",
    elemento: "Morte",
    circulo: 3,
    execucao: "Padrão",
    alcance: "Médio",
    alvoAreaEfeito: "Área: Círculo com 6m de raio",
    duracao: "Cena",
    custoPE: 6,
    descricao: "Tentáculos surgem na fenda (terreno difícil, imunes a dano). No início do seu turno, faz manobra Agarrar com Ocultismo contra todos na área. Se agarrar (ou já estiver), alvo sofre 4d6 de dano (metade Impacto, Morte).",
    verdadeiro: "(+5 PE): aumenta a área para 9m de raio e o dano para 6d6.",
  ),
  Ritual(
    nome: "Transfigurar Água",
    elemento: "Energia",
    circulo: 3,
    execucao: "Padrão",
    alcance: "Longo",
    alvoAreaEfeito: "Área: Esfera de 30m",
    duracao: "Cena",
    custoPE: 6,
    resistencia: "Varia",
    descricao: "Escolha: \nCongelar: Imobiliza quem nada (escapa com ação padrão/Atletismo).\nDerreter: Água descongela.\nEnchente: Sobe água em 4,5m (ou dá +6m desl. p/ embarcação).\nEvaporar: Seca água/gelo e causa 5d8 Energia nos vivos (Fortitude reduz metade).\nPartir: Baixa nível em 4,5m (abre caminho) ou cria redemoinho fatal p/ barcos.",
    verdadeiro: "(+5 PE): aumenta desl. da enchente para +12m e dano de evaporar para 10d8.",
  ),
  Ritual(
    nome: "Transfigurar Terra",
    elemento: "Energia",
    circulo: 3,
    execucao: "Padrão",
    alcance: "Longo",
    alvoAreaEfeito: "Área: 9 cubos de 1,5m",
    duracao: "Instantânea",
    custoPE: 6,
    resistencia: "Varia",
    descricao: "Escolha:\nAmolecer: Derruba tetos (10d6 Impacto, Reflexos metade) ou cria terreno difícil.\nModelar: Cria objetos gigantes (ex: ponte, muro que dá Cobertura Total com RD 8 e 50 PV).\nSolidificar: Prende pés na areia/lama (escapa com ação padrão/Atletismo).",
    discente: "(+3 PE): muda área para 15 cubos.",
    verdadeiro: "(+7 PE): passa a afetar todos os minerais e metais. Requer 4º círculo.",
  ),
  Ritual(
    nome: "Vidência",
    elemento: "Conhecimento",
    circulo: 3,
    execucao: "Completa",
    alcance: "Ilimitado",
    alvoAreaEfeito: "Alvo: 1 ser",
    duracao: "5 rodadas",
    custoPE: 6,
    resistencia: "Vontade anula",
    descricao: "Vê e ouve o alvo e 6m em volta via reflexo. O alvo testa Vontade todo turno para bloquear o ritual. Dois sucessos encerram e dão imunidade de 1 semana. Exige item/foto/nome do alvo (DT da Vontade varia por familiaridade).",
  ),
  Ritual(
    nome: "Vomitar Pestes",
    elemento: "Sangue",
    circulo: 3,
    execucao: "Padrão",
    alcance: "Médio",
    alvoAreaEfeito: "Efeito: Enxame Grande (3m)",
    duracao: "Sustentada",
    custoPE: 6,
    resistencia: "Reflexos reduz metade",
    descricao: "No final dos seus turnos, o enxame causa 5d12 de Sangue em quem dividir o espaço com ele. Pode ser movido 12m com ação de movimento.",
    discente: "(+2 PE): falha no Reflexos = alvo Agarrado pelo enxame. Escapa com ação Padrão (Acrobacia/Atletismo). Mover o enxame solta a vítima.",
    verdadeiro: "(+5 PE): o enxame fica Enorme (6m) e ganha deslocamento de Voo 18m.",
  ),
  Ritual(
    nome: "Zerar Entropia",
    elemento: "Morte",
    circulo: 3,
    execucao: "Padrão",
    alcance: "Curto",
    alvoAreaEfeito: "Alvo: 1 pessoa",
    duracao: "Cena",
    custoPE: 6,
    resistencia: "Vontade parcial",
    descricao: "O alvo fica Paralisado (ou Lento se passar na resistência). Pode usar ação Completa para re-testar Vontade e encerrar.",
    discente: "(+4 PE): afeta 1 ser não-humano. Requer 4º círculo.",
    verdadeiro: "(+11 PE): afeta seres escolhidos. Requer 4º círculo e afinidade.",
  ),
  Ritual(
    nome: "Odor da Caçada",
    elemento: "Sangue",
    circulo: 3,
    execucao: "Reação",
    alcance: "Pessoal",
    alvoAreaEfeito: "Alvo: Você",
    duracao: "Cena",
    custoPE: 6,
    descricao: "Recebe Faro. Em Perseguição, ganha +5 Atletismo e não perde PV por esforço extra (se caça/caçador emitir cheiro). Na próxima cena, sofre de Fome/Sede mágicas.",
    discente: "(+4 PE): alcance vira toque, alvo 1 ser.",
    verdadeiro: "(+9 PE): alcance curto, até 5 seres. Requer afinidade.",
  ),
  Ritual(
    nome: "Fedor Pútrido",
    elemento: "Morte",
    circulo: 3,
    execucao: "Padrão",
    alcance: "Pessoal",
    alvoAreaEfeito: "Alvo: Você",
    duracao: "Sustentada",
    custoPE: 6,
    descricao: "Você cheira a cadáver. Animais fogem, você sofre -3d20 Diplomacia, +5 Furtividade, +10 Enganação (Fingir de morto). Em Perseguição, visibilidade cai em 1 se ficar parado. Causa 1d4 dano de Morte fixo/rodada.",
    discente: "(+4 PE): alcance vira toque, alvo 1 ser voluntário.",
    verdadeiro: "(+9 PE): alcance curto, até 5 voluntários. Requer afinidade.",
  ),
  Ritual(
    nome: "Relembrar Fragmento",
    elemento: "Conhecimento",
    circulo: 3,
    execucao: "Padrão",
    alcance: "Toque",
    alvoAreaEfeito: "Alvo: 1 objeto",
    duracao: "Instantânea",
    custoPE: 6,
    descricao: "Restaura texto danificado se tocar um pedaço original. Permanece legível apenas enquanto você tocar.",
    discente: "(+4 PE): o item fica restaurado até o fim da missão.",
    verdadeiro: "(+9 PE): pode alterar o texto original para o que você quiser falsificar. Dura até fim da missão. Requer afinidade.",
  ),
  Ritual(
    nome: "Mutar",
    elemento: "Energia",
    circulo: 3,
    execucao: "Padrão",
    alcance: "Pessoal",
    alvoAreaEfeito: "Alvo: Você",
    duracao: "Cena",
    custoPE: 6,
    descricao: "Você anula qualquer som de/para você. Passos e tiros são mudos (Você fica Surdo). Dá +10 Furtividade e reduz aumento de visibilidade em 1. Falar (como player) quebra o ritual.",
    discente: "(+4 PE): alcance toque, 1 ser.",
    verdadeiro: "(+9 PE): alcance curto, 5 seres. Requer afinidade.",
  ),
  Ritual(
    nome: "Milagre Ionizante",
    elemento: "Energia",
    circulo: 3,
    execucao: "Completa",
    alcance: "Toque",
    alvoAreaEfeito: "Alvo: 1 ser",
    duracao: "Instantânea",
    custoPE: 6,
    descricao: "Cura o alvo de UMA condição mundana ou paranormal não-permanente (não cura Energia). Após curado, o alvo testa Fortitude DT 30. Se falhar, pega a doença 'Infectcídio'.",
  ),

  // ==========================================
  // RITUAIS DE 4º CÍRCULO
  // ==========================================
  Ritual(
    nome: "Controle Mental",
    elemento: "Conhecimento",
    circulo: 4,
    execucao: "Padrão",
    alcance: "Médio",
    alvoAreaEfeito: "Alvo: 1 pessoa ou animal",
    duracao: "Sustentada",
    custoPE: 10,
    resistencia: "Vontade parcial",
    descricao: "Domina a mente do alvo, que obedece tudo (exceto ordens suicidas). O alvo re-testa Vontade no fim dos turnos dele para escapar (se escapar, fica pasmo por 1 rodada).",
    discente: "(+5 PE): domina até 5 pessoas/animais.",
    verdadeiro: "(+10 PE): domina até 10 pessoas/animais. Requer afinidade.",
  ),
  Ritual(
    nome: "Convocar o Algoz",
    elemento: "Morte",
    circulo: 4,
    execucao: "Padrão",
    alcance: "1,5m",
    alvoAreaEfeito: "Alvo: 1 pessoa",
    duracao: "Sustentada",
    custoPE: 10,
    resistencia: "Vontade parcial, Fortitude parcial",
    descricao: "Cria vulto assustador (só o alvo enxerga o detalhe). Move-se 12m por turno na direção do alvo. Se ficar Curto, alvo testa Vontade (falha=Abalado). Se ficar adjacente, alvo testa Fortitude (falha=Colapso para 0 PV; Sucesso=6d6 Morte). É incorpóreo/imune a dano.",
  ),
  Ritual(
    nome: "Deflagração de Energia",
    elemento: "Energia",
    circulo: 4,
    execucao: "Completa",
    alcance: "Pessoal",
    alvoAreaEfeito: "Área: Explosão de 15m",
    duracao: "Instantânea",
    custoPE: 10,
    resistencia: "Fortitude parcial",
    descricao: "Explosão suprema de 30d10 (3d10x10) de Energia que quebra todos os itens tecnológicos na área. Você é imune. Passar em Fortitude = metade do dano e itens religam em 1d4 rodadas.",
    verdadeiro: "(+5 PE): afeta apenas alvos a sua escolha.",
  ),
  Ritual(
    nome: "Distorção Temporal",
    elemento: "Morte",
    circulo: 4,
    execucao: "Padrão",
    alcance: "Pessoal",
    alvoAreaEfeito: "Alvo: Você",
    duracao: "3 rodadas (bolsão temporal)",
    custoPE: 10,
    descricao: "Gera um bolsão em que o tempo para. Você pode agir livremente por 3 turnos, mas não pode mover-se nem interagir com outros objetos/seres (nem eles com você).",
  ),
  Ritual(
    nome: "Fim Inevitável",
    elemento: "Morte",
    circulo: 4,
    execucao: "Completa",
    alcance: "Extremo",
    alvoAreaEfeito: "Efeito: Buraco negro de 1,5m",
    duracao: "4 rodadas",
    custoPE: 10,
    resistencia: "Fortitude parcial",
    descricao: "Buraco negro atrai quem está a 90m (inclusive você). No início do turno, teste Fortitude (falha = Caído e puxado 30m). Tocar no buraco = 100 de Morte/rodada. Agarrar objetos fixos dá +5 na Fortitude.",
    discente: "(+5 PE): dura 5 rodadas e VOCÊ não é puxado. Requer afinidade.",
    verdadeiro: "(+10 PE): dura 6 rodadas e alvos escolhidos não são puxados. Requer afinidade.",
  ),
  Ritual(
    nome: "Inexistir",
    elemento: "Conhecimento",
    circulo: 4,
    execucao: "Padrão",
    alcance: "Toque",
    alvoAreaEfeito: "Alvo: 1 ser",
    duracao: "Instantânea",
    custoPE: 10,
    resistencia: "Vontade parcial",
    descricao: "Apaga a mente/corpo. Causa 10d12+10 de Conhecimento. Se passar, sofre só 2d12 e fica debilitado. Se o dano zerar os PV da criatura (mesmo com sucesso no teste), ela é apagada da existência completamente.",
    discente: "(+5 PE): dano vira 15d12+15. Dano resistido vira 3d12.",
    verdadeiro: "(+10 PE): dano vira 20d12+20. Dano resistido vira 4d12. Requer afinidade.",
  ),
  Ritual(
    nome: "Invólucro de Carne",
    elemento: "Sangue",
    circulo: 4,
    execucao: "Padrão",
    alcance: "Curto",
    alvoAreaEfeito: "Efeito: 1 clone seu",
    duracao: "Cena",
    custoPE: 10,
    descricao: "Cria um clone seu de sangue e equipamentos mundanos. Sem mente, só age sob ordens (ação movimento) ou você pode assumir controle manual dele no seu turno. Desfaz ao zerar PV.",
  ),
  Ritual(
    nome: "Lâmina do Medo",
    elemento: "Medo",
    circulo: 4,
    execucao: "Padrão",
    alcance: "Toque",
    alvoAreaEfeito: "Alvo: 1 ser",
    duracao: "Instantânea",
    custoPE: 10,
    resistencia: "Fortitude parcial",
    descricao: "Golpeia com a Realidade rasgada. Falha em Fortitude: PV cai para 0. Sucesso: Sofre 10d8 de Medo absoluto (ignora RD) e fica apavorado. Ferimento nunca cicatriza.",
  ),
  Ritual(
    nome: "Medo Tangível",
    elemento: "Medo",
    circulo: 4,
    execucao: "Padrão",
    alcance: "Pessoal",
    alvoAreaEfeito: "Alvo: Você",
    duracao: "Cena",
    custoPE: 10,
    descricao: "Você vira a manifestação do Medo. Imune à maioria das condições (atordoado, cego, paralisado, etc), furtivos/críticos e DANO FÍSICO não pode zerar seu PV (mínimo trava no 1).",
  ),
  Ritual(
    nome: "Possessão",
    elemento: "Conhecimento",
    circulo: 4,
    execucao: "Padrão",
    alcance: "Longo",
    alvoAreaEfeito: "Alvo: 1 ser vivo/morto",
    duracao: "1 dia",
    custoPE: 10,
    resistencia: "Vontade anula",
    descricao: "Transfere sua consciência. Você usa os stats físicos (For/Agi/Vig/Desl) do alvo. Se um dos corpos morrer, a mente encalha. Retornar é ação livre.",
  ),
  Ritual(
    nome: "Presença do Medo",
    elemento: "Medo",
    circulo: 4,
    execucao: "Padrão",
    alcance: "Pessoal",
    alvoAreaEfeito: "Área: 9m raio",
    duracao: "Sustentada",
    custoPE: 10,
    resistencia: "Vontade reduz metade",
    descricao: "Todo ser que entrar ou iniciar na área sofre 5d8 de Medo e 5d8 de dano Mental (Vontade metade). Falha resulta em atordoamento por 1 rodada (só atordoa 1x/cena).",
  ),
  Ritual(
    nome: "Teletransporte",
    elemento: "Energia",
    circulo: 4,
    execucao: "Padrão",
    alcance: "Toque",
    alvoAreaEfeito: "Alvo: Até 5 voluntários",
    duracao: "Instantânea",
    custoPE: 10,
    descricao: "Desloca alvos a até 1.000km. Exige teste de Ocultismo (DT 25 muito familiar, DT 30 já visitou, DT 35 descrição alheia). Falha erra a rota (1d10x10 km). Falha > 5, atordoa o grupo.",
    verdadeiro: "(+5 PE): destrava teleporte para qualquer lugar do globo.",
  ),
  Ritual(
    nome: "Vínculo de Sangue",
    elemento: "Sangue",
    circulo: 4,
    execucao: "Padrão",
    alcance: "Curto",
    alvoAreaEfeito: "Alvo: 1 ser",
    duracao: "Cena",
    custoPE: 10,
    resistencia: "Fortitude anula",
    descricao: "Cria ligação de dano: você ou o inimigo pode rachar o dano sofrido com o outro. Inimigos podem testar Fortitude para anular.",
  ),
  Ritual(
    nome: "Pronunciar Sigilo",
    elemento: "Conhecimento",
    circulo: 4,
    execucao: "Padrão",
    alcance: "Curto",
    alvoAreaEfeito: "Alvo: 1 ser",
    duracao: "Varia",
    custoPE: 10,
    resistencia: "Vontade parcial",
    descricao: "Grite a palavra profana. Escolha: Esquecer (Atordoa por 1d4+1, sucesso = Desprevenido); Cegar (Cego, sucesso = Ofuscado); Inexistir (Some da Realidade por 1d4+1 rodadas. Sucesso = Some 1 rodada).",
    discente: "(+5 PE): alcance Extremo.",
    verdadeiro: "(+10 PE): afeta 5 seres. Requer afinidade.",
  ),
  Ritual(
    nome: "Singularidade Temporal",
    elemento: "Morte",
    circulo: 4,
    execucao: "Padrão",
    alcance: "Curto",
    alvoAreaEfeito: "Alvo: 1 objeto mundano (Médio)",
    duracao: "Instantânea",
    custoPE: 10,
    resistencia: "Fortitude evita (se segurado)",
    descricao: "Avança o tempo do objeto fazendo-o apodrecer ou quebrar. Aplica debuffs gigantes ou o destrói por completo, se a constituição permitir.",
    discente: "(+5 PE): objeto Grande.",
    verdadeiro: "(+10 PE): objeto Enorme.",
  ),
  Ritual(
    nome: "Martírio de Sangue",
    elemento: "Sangue",
    circulo: 4,
    execucao: "Padrão",
    alcance: "Pessoal",
    alvoAreaEfeito: "Alvo: Você",
    duracao: "Infinita",
    custoPE: 10,
    descricao: "Sacrifício Supremo. Ganha Faro, Visão Escuro, Cura 10, +10 (Ataques/Dano/Defesa), 30 PV Temp, +1 dado Dano Corpo a Corpo letal. Perde a mente (-3d20 testes sociais). Ao final da Cena, você morre e o char vira uma Criatura do Mestre para sempre.",
    discente: "(+5 PE): Bônus = +20, PV Temp = 50. Requer afinidade.",
  ),
];